import Head from "next/head";
import Image from "next/image";
import { useStats } from "../shared/queries";

export default function Home() {
  const { data } = useStats();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="">
          <h1 className="text-3xl font-bold underline">Hello world!</h1>
        </div>
      </main>
    </div>
  );
}
